import Link from 'next/link';

const platforms = [
  ['TikTok','Available for connected accounts'],
  ['Facebook','Coming soon'],
  ['Instagram','Coming soon'],
  ['YouTube','Coming soon'],
];

export default function Home(){return <main>
  <nav className="nav shell"><Link className="brand" href="/">Hoai<span>Studio</span></Link><div className="navlinks"><a href="#product">Product</a><a href="#how">How it works</a><a href="#platforms">Platforms</a></div><div className="actions"><Link className="quiet" href="/login">Log in</Link><Link className="button small" href="/signup">Get started</Link></div></nav>
  <section className="hero shell"><div className="eyebrow">SOCIAL PUBLISHING, SIMPLIFIED</div><h1>Your content.<br/><em>One focused workspace.</em></h1><p className="lead">Create a cleaner publishing workflow for the social accounts you manage. Connect your account, prepare your post, review every setting, and publish with confidence.</p><div className="heroActions"><Link className="button" href="/signup">Start with HoaiStudio <b>→</b></Link><a className="textLink" href="#how">See how it works</a></div><div className="trust"><span>✓ You control every connection</span><span>✓ Publish only when you choose</span><span>✓ Built for original content</span></div></section>
  <section className="product shell" id="product"><div className="sectionCopy"><div className="eyebrow">A CALMER WAY TO PUBLISH</div><h2>Everything important stays visible.</h2><p>HoaiStudio brings account connection, content preparation, publishing controls and post status into one straightforward experience.</p></div><div className="mock"><div className="mockTop"><span className="dots">● ● ●</span><strong>HoaiStudio</strong><span>Workspace</span></div><div className="mockBody"><aside><b>Overview</b><span className="active">TikTok</span><span>Content</span><span>Connected accounts</span><span>Settings</span></aside><div className="panel"><div className="panelHead"><div><small>TIKTOK</small><h3>Ready when you are.</h3></div><span className="connected">● Connected</span></div><div className="upload"><div className="play">▶</div><div><b>Your video</b><span>Review your content before publishing</span></div><button>Replace</button></div><label>Caption</label><div className="field">Share something worth watching…</div><div className="settings"><div><small>PRIVACY</small><b>Choose before publishing</b></div><div><small>INTERACTIONS</small><b>Comments · Duet · Stitch</b></div></div><button className="publish">Review & publish</button></div></div></div></section>
  <section className="steps" id="how"><div className="shell"><div className="eyebrow">HOW IT WORKS</div><h2>From account connection to published post.</h2><div className="stepGrid"><article><span>01</span><h3>Create your workspace</h3><p>Sign in to HoaiStudio and keep your publishing activity organized in one place.</p></article><article><span>02</span><h3>Connect your account</h3><p>Authorize a supported social account. You stay in control of access and can disconnect it.</p></article><article><span>03</span><h3>Prepare and review</h3><p>Add your content, caption and available publishing preferences before anything is sent.</p></article><article><span>04</span><h3>Publish with intent</h3><p>Confirm the post yourself, then follow its publishing status from your workspace.</p></article></div></div></section>
  <section className="platformSection shell" id="platforms"><div><div className="eyebrow">PLATFORMS</div><h2>Start focused. Grow from there.</h2><p>HoaiStudio is beginning with a focused TikTok publishing experience. Additional platform workflows are planned as the product grows.</p></div><div className="platforms">{platforms.map(([n,s])=><div className="platform" key={n}><strong>{n}</strong><span>{s}</span></div>)}</div></section>
  <section className="cta shell"><div><div className="eyebrow">YOUR WORKSPACE</div><h2>Make publishing feel manageable again.</h2><p>Set up your HoaiStudio account and connect supported platforms when you are ready.</p></div><Link className="button light" href="/signup">Create account →</Link></section>
  <footer><div className="shell footer"><div><Link className="brand" href="/">Hoai<span>Studio</span></Link><p>A focused social publishing workspace.</p></div><div className="footerLinks"><div><b>Product</b><a href="#how">How it works</a><a href="#platforms">Platforms</a><Link href="/login">Log in</Link></div><div><b>Company</b><Link href="/about">About</Link><Link href="/contact">Contact</Link></div><div><b>Legal</b><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div></div><div className="shell copyright">© 2026 HoaiStudio. All rights reserved.</div></footer>
</main>}
