import Link from 'next/link';

const platforms = [
  ['TikTok','Integration in review'],
  ['Facebook','Planned'],
  ['Instagram','Planned'],
  ['YouTube','Planned'],
];

export default function Home(){return <main>
  <nav className="nav shell"><Link className="brand" href="/">Hoai<span>Studio</span></Link><div className="navlinks"><a href="#product">Product</a><a href="#how">How it works</a><a href="#platforms">Platforms</a></div><div className="actions"><Link className="quiet" href="/login">Log in</Link><Link className="button small" href="/signup">Get started</Link></div></nav>
  <section className="hero shell"><div className="eyebrow">CREATOR PUBLISHING WORKSPACE</div><h1>Prepare with clarity.<br/><em>Publish with control.</em></h1><p className="lead">HoaiStudio is a focused workspace for creators to prepare original content, connect an authorized social account, review platform-specific settings, and intentionally submit each post.</p><div className="heroActions"><Link className="button" href="/signup">Create your workspace <b>→</b></Link><a className="textLink" href="#how">See the workflow</a></div><div className="trust"><span>✓ Explicit account authorization</span><span>✓ Review settings before submission</span><span>✓ You initiate every publish action</span></div></section>
  <section className="product shell" id="product"><div className="sectionCopy"><div className="eyebrow">DESIGNED AROUND CREATOR CONTROL</div><h2>The important choices stay visible.</h2><p>HoaiStudio keeps account identity, content, caption, privacy and available interaction controls together so creators can review the destination and settings before a publishing request is submitted.</p><div className="miniProof"><b>Built for original creator content</b><span>Account authorization and publishing are separate actions.</span><span>No post is submitted simply because an account is connected.</span></div></div><div className="mock"><div className="mockTop"><span className="dots">● ● ●</span><strong>HoaiStudio</strong><span>Publish review</span></div><div className="mockBody"><aside><b>Workspace</b><span className="active">TikTok</span><span>Content</span><span>Connected account</span><span>Settings</span></aside><div className="panel"><div className="panelHead"><div><small>TIKTOK</small><h3>Review before publishing.</h3></div><span className="connected">● Authorized</span></div><div className="creatorRow"><div className="creatorAvatar">H</div><div><small>DESTINATION ACCOUNT</small><b>Creator identity appears here</b></div></div><div className="upload"><div className="play">▶</div><div><b>Your original video</b><span>Review the selected media before publishing</span></div><button>Replace</button></div><label>Caption</label><div className="field">Write a caption for your post…</div><div className="settings"><div><small>PRIVACY</small><b>Select an available option</b></div><div><small>INTERACTIONS</small><b>Comments · Duet · Stitch</b></div></div><div className="consentRow">□ I have reviewed this post and want to send it to TikTok.</div><button className="publish">Review & publish</button></div></div></div></section>
  <section className="steps" id="how"><div className="shell"><div className="eyebrow">HOW IT WORKS</div><h2>A deliberate path from connection to publishing.</h2><div className="stepGrid"><article><span>01</span><h3>Create a workspace</h3><p>Create a HoaiStudio account so your connected-account and publishing workflow has a clear home.</p></article><article><span>02</span><h3>Authorize TikTok</h3><p>Choose Connect TikTok and complete TikTok’s own authorization and consent flow. You control the permission grant.</p></article><article><span>03</span><h3>Prepare the post</h3><p>Select original content and review the current creator identity, caption, privacy choices and available interaction settings.</p></article><article><span>04</span><h3>Confirm and submit</h3><p>Nothing is submitted until you review the post and intentionally choose the publishing action.</p></article></div></div></section>
  <section className="platformSection shell" id="platforms"><div><div className="eyebrow">PLATFORMS</div><h2>Focused on TikTok first.</h2><p>The first HoaiStudio integration is being built around TikTok’s official authorization and Content Posting APIs. Other platform workflows are planned, but are not represented as available today.</p></div><div className="platforms">{platforms.map(([n,s])=><div className="platform" key={n}><strong>{n}</strong><span>{s}</span></div>)}</div></section>
  <section className="reviewSection shell"><div><div className="eyebrow">TRANSPARENT BY DESIGN</div><h2>Authorization is not publication.</h2></div><div className="reviewCards"><article><b>Connect intentionally</b><p>Social account access begins only after the creator chooses to connect and completes the platform authorization flow.</p></article><article><b>Review current controls</b><p>Publishing choices are presented in the workspace so the creator can review available settings for the connected account.</p></article><article><b>Publish intentionally</b><p>HoaiStudio requires a separate creator action to submit a prepared post. Connecting an account does not trigger publication.</p></article></div></section>
  <section className="cta shell"><div><div className="eyebrow">YOUR WORKSPACE</div><h2>A simpler place to prepare the next post.</h2><p>Create a HoaiStudio workspace and connect supported accounts when you are ready.</p></div><Link className="button light" href="/signup">Create account →</Link></section>
  <footer><div className="shell footer"><div><Link className="brand" href="/">Hoai<span>Studio</span></Link><p>A focused creator publishing workspace.</p></div><div className="footerLinks"><div><b>Product</b><a href="#product">Product</a><a href="#how">How it works</a><a href="#platforms">Platforms</a></div><div><b>Company</b><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/login">Log in</Link></div><div><b>Legal</b><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></div></div></div><div className="shell copyright">© 2026 HoaiStudio. All rights reserved.</div></footer>
</main>}
