import Link from 'next/link';

const platforms=[['TikTok','Primary publishing workflow'],['Facebook','Planned'],['Instagram','Planned'],['YouTube','Planned']];

export default function Home(){return <main>
<nav className="nav shell"><Link className="brand" href="/">Hoai<span>Studio</span></Link><div className="navlinks"><a href="#product">Product</a><a href="#how">How it works</a><a href="#platforms">Platforms</a></div><div className="actions"><Link className="quiet" href="/login">Log in</Link><Link className="button small" href="/signup">Get started</Link></div></nav>
<section className="hero shell"><div className="eyebrow">CREATOR PUBLISHING WORKSPACE</div><h1>Prepare with clarity.<br/><em>Publish with control.</em></h1><p className="lead">HoaiStudio gives creators one focused place to prepare original content, connect an authorized account, review platform-specific choices, and intentionally submit each post.</p><div className="heroActions"><Link className="button" href="/signup">Create your workspace <b>→</b></Link><a className="textLink" href="#how">See the workflow</a></div><div className="trust"><span>✓ Explicit account authorization</span><span>✓ Review settings before submission</span><span>✓ You initiate every publish action</span></div></section>
<section className="product shell" id="product"><div className="sectionCopy"><div className="eyebrow">DESIGNED AROUND CREATOR CONTROL</div><h2>The important choices stay visible.</h2><p>Account identity, selected media, caption, privacy, interaction controls, and commercial-content choices belong in the same review flow—before anything is sent.</p><div className="miniProof"><b>Built for original creator content</b><span>Account authorization and publishing are separate actions.</span><span>Publishing choices remain editable until the creator submits.</span><span>Post status stays visible after submission.</span></div></div><div className="mock"><div className="mockTop"><span className="dots">● ● ●</span><strong>HoaiStudio</strong><span>Publish review</span></div><div className="mockBody"><aside><b>Workspace</b><span className="active">TikTok</span><span>Content</span><span>Connected account</span><span>Settings</span></aside><div className="panel"><div className="panelHead"><div><small>TIKTOK</small><h3>Review before publishing.</h3></div><span className="connected">● Authorized</span></div><div className="creatorRow"><div className="creatorAvatar">H</div><div><small>DESTINATION ACCOUNT</small><b>Creator nickname</b></div></div><div className="upload"><div className="play">▶</div><div><b>Your original video</b><span>Preview the selected media before publishing</span></div><button>Replace</button></div><label>Caption</label><div className="field">Write a caption for your post…</div><div className="settings"><div><small>PRIVACY</small><b>Select an available option</b></div><div><small>INTERACTIONS</small><b>Comments · Duet · Stitch</b></div></div><div className="disclosure"><small>CONTENT DISCLOSURE</small><b>Promotional content</b><span>Off by default · creator controlled</span></div><div className="consentRow">□ By posting, you agree to TikTok’s Music Usage Confirmation.</div><button className="publish">Publish to TikTok</button><p className="processingNote">After publishing, processing may take a few minutes before the post is visible on the connected profile.</p></div></div></div></section>
<section className="steps" id="how"><div className="shell"><div className="eyebrow">HOW IT WORKS</div><h2>A deliberate path from connection to publishing.</h2><div className="stepGrid"><article><span>01</span><h3>Create a workspace</h3><p>Keep connected-account and publishing activity organized under your HoaiStudio account.</p></article><article><span>02</span><h3>Authorize your account</h3><p>Choose Connect TikTok and complete TikTok’s authorization flow. The creator controls the permission grant.</p></article><article><span>03</span><h3>Prepare and review</h3><p>Select original content and review the current creator identity, caption, privacy, interactions, and disclosure choices.</p></article><article><span>04</span><h3>Confirm and submit</h3><p>Nothing is submitted until the creator reviews the post, confirms the required declaration, and chooses Publish.</p></article></div></div></section>
<section className="platformSection shell" id="platforms"><div><div className="eyebrow">PLATFORMS</div><h2>Focused on TikTok first.</h2><p>HoaiStudio’s first connected publishing workflow is designed around TikTok’s official authorization and Content Posting interfaces. Additional platform workflows can be added without changing the creator-first publishing model.</p></div><div className="platforms">{platforms.map(([n,s])=><div className="platform" key={n}><strong>{n}</strong><span>{s}</span></div>)}</div></section>
<section className="reviewSection shell"><div><div className="eyebrow">TRANSPARENT BY DESIGN</div><h2>Authorization is not publication.</h2></div><div className="reviewCards"><article><b>Know the destination</b><p>The connected creator identity stays visible so users know which account will receive the post.</p></article><article><b>Choose every setting</b><p>Privacy, interactions, disclosures, and editable post text remain creator-controlled rather than silently preselected.</p></article><article><b>Publish intentionally</b><p>HoaiStudio requires a separate creator action to submit a prepared post and keeps publishing status visible afterward.</p></article></div></section>
<section className="cta shell"><div><div className="eyebrow">YOUR WORKSPACE</div><h2>A simpler place to prepare the next post.</h2><p>Create a HoaiStudio workspace and connect a supported account when you are ready.</p></div><Link className="button light" href="/signup">Create account →</Link></section>
<footer><div className="shell footer"><div><Link className="brand" href="/">Hoai<span>Studio</span></Link><p>A focused creator publishing workspace.</p><a className="footerMail" href="mailto:contact@hoaidang.com">contact@hoaidang.com</a></div><div className="footerLinks"><div><b>Product</b><a href="#product">Product</a><a href="#how">How it works</a><a href="#platforms">Platforms</a></div><div><b>Company</b><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/login">Log in</Link></div><div><b>Legal</b><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></div></div></div><div className="shell copyright">© 2026 HoaiStudio. All rights reserved.</div></footer>
</main>}
