'use client';

import { useEffect, useMemo, useState } from 'react';

const label={PUBLIC_TO_EVERYONE:'Public',MUTUAL_FOLLOW_FRIENDS:'Friends',FOLLOWER_OF_CREATOR:'Followers',SELF_ONLY:'Only me'};
const MUSIC_URL='https://www.tiktok.com/legal/page/global/music-usage-confirmation/en';
const BRANDED_URL='https://www.tiktok.com/legal/page/global/bc-policy/en';

async function jsonFetch(url,options){const r=await fetch(url,options);const j=await r.json().catch(()=>({}));if(!r.ok||(j.error?.code&&j.error.code!=='ok'))throw new Error(j.error?.message||j.error?.code||j.error||`Request failed (${r.status})`);return j}

export default function TikTokPublisher(){
 const [creator,setCreator]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [file,setFile]=useState(null),[preview,setPreview]=useState(''),[duration,setDuration]=useState(0),[title,setTitle]=useState(''),[privacy,setPrivacy]=useState('');
 const [comment,setComment]=useState(false),[duet,setDuet]=useState(false),[stitch,setStitch]=useState(false);
 const [commercial,setCommercial]=useState(false),[ownBrand,setOwnBrand]=useState(false),[branded,setBranded]=useState(false),[aigc,setAigc]=useState(false),[consent,setConsent]=useState(false);
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[publishId,setPublishId]=useState(''),[status,setStatus]=useState('');
 useEffect(()=>{(async()=>{try{const j=await jsonFetch('/api/tiktok/creator',{cache:'no-store'});setCreator(j.data)}catch(e){setError(e.message)}finally{setLoading(false)}})()},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const maxDuration=creator?.max_video_post_duration_sec||0;
 const durationOK=!file||(duration>0&&(!maxDuration||duration<=maxDuration));
 const commercialOK=!commercial||ownBrand||branded;
 const brandedPrivacyOK=!branded||privacy!=='SELF_ONLY';
 const ready=useMemo(()=>Boolean(file&&durationOK&&privacy&&consent&&commercialOK&&brandedPrivacyOK&&!busy),[file,durationOK,privacy,consent,commercialOK,brandedPrivacyOK,busy]);

 function chooseFile(f){if(preview)URL.revokeObjectURL(preview);setFile(f||null);setPreview(f?URL.createObjectURL(f):'');setDuration(0);setProgress(0);setPublishId('');setStatus('');setError('');setConsent(false)}
 async function uploadChunks(uploadUrl,plan){const chunk=plan.chunk_size,count=plan.total_chunk_count,total=file.size;let start=0;for(let i=0;i<count;i++){const end=i===count-1?total:Math.min(start+chunk,total);const blob=file.slice(start,end);const r=await fetch(uploadUrl,{method:'PUT',headers:{'Content-Type':file.type||'video/mp4','Content-Length':String(blob.size),'Content-Range':`bytes ${start}-${end-1}/${total}`},body:blob});if(!(r.status===206||r.status===201||r.ok))throw new Error(`TikTok upload failed (${r.status})`);start=end;setProgress(Math.round(start/total*100))}}
 async function publish(){if(!ready)return;setBusy(true);setError('');setStatus('Initializing secure upload…');setProgress(0);try{const j=await jsonFetch('/api/tiktok/publish/init',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_size:file.size,title,privacy_level:privacy,disable_comment:!comment,disable_duet:!duet,disable_stitch:!stitch,brand_organic_toggle:commercial&&ownBrand,brand_content_toggle:commercial&&branded,is_aigc:aigc})});const d=j.data;if(!d?.upload_url||!d?.publish_id)throw new Error('TikTok did not return an upload session.');setPublishId(d.publish_id);setStatus('Uploading directly to TikTok…');await uploadChunks(d.upload_url,d.upload_plan);setStatus('Upload complete. TikTok is processing the post; this may take a few minutes.')}catch(e){setError(e.message);setStatus('')}finally{setBusy(false)}}
 async function checkStatus(){try{setBusy(true);const j=await jsonFetch('/api/tiktok/publish/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publish_id:publishId})});setStatus(j.data?.status||'Status received from TikTok.')}catch(e){setError(e.message)}finally{setBusy(false)}}

 if(loading)return <div className="publisherCard"><p>Loading latest TikTok creator settings…</p></div>;
 if(error&&!creator)return <div className="publisherCard"><h2>TikTok connection needs attention</h2><p>{error}</p><a className="connectButton" href="/api/tiktok/connect">Reconnect TikTok →</a></div>;
 return <div className="publisherGrid">
  <section className="publisherCard"><small>AUTHORIZED CREATOR</small><div className="creatorRow">{creator?.creator_avatar_url&&<img src={creator.creator_avatar_url} alt=""/>}<div><h2>{creator?.creator_nickname||'TikTok creator'}</h2><p>@{creator?.creator_username||'connected account'}</p></div><b>CONNECTED ✓</b></div><p>HoaiStudio loads TikTok's latest posting permissions before every publishing session.</p></section>
  <section className="publisherCard"><small>1 · ORIGINAL CONTENT</small><h2>Select and preview a video</h2><input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={e=>chooseFile(e.target.files?.[0]||null)}/>{file&&<><p><b>{file.name}</b> · {(file.size/1048576).toFixed(1)} MB</p><video className="tiktokPreview" src={preview} controls playsInline onLoadedMetadata={e=>setDuration(e.currentTarget.duration||0)}/>{duration>0&&<p>Duration: {duration.toFixed(1)}s{maxDuration?` · TikTok limit: ${maxDuration}s`:''}</p>}{!durationOK&&<div className="authError">This video exceeds the posting duration TikTok returned for this creator.</div>}</>}</section>
  <section className="publisherCard"><small>2 · POST DETAILS</small><h2>Review before publishing</h2><label>Caption<textarea value={title} maxLength={2200} onChange={e=>setTitle(e.target.value)} placeholder="Write your caption, hashtags and mentions…"/></label><p>{title.length}/2200</p><label>Who can view<select value={privacy} onChange={e=>{setPrivacy(e.target.value);setConsent(false)}}><option value="" disabled>Select privacy…</option>{(creator?.privacy_level_options||[]).map(x=><option key={x} value={x} disabled={x==='SELF_ONLY'&&branded}>{label[x]||x}</option>)}</select></label><div className="publishChecks"><label><input type="checkbox" checked={comment} disabled={creator?.comment_disabled} onChange={e=>setComment(e.target.checked)}/> Allow comments</label><label><input type="checkbox" checked={duet} disabled={creator?.duet_disabled} onChange={e=>setDuet(e.target.checked)}/> Allow Duet</label><label><input type="checkbox" checked={stitch} disabled={creator?.stitch_disabled} onChange={e=>setStitch(e.target.checked)}/> Allow Stitch</label><label><input type="checkbox" checked={aigc} onChange={e=>setAigc(e.target.checked)}/> This content is AI-generated</label></div>
   <div className="commercialBox"><label><input type="checkbox" checked={commercial} onChange={e=>{const on=e.target.checked;setCommercial(on);if(!on){setOwnBrand(false);setBranded(false)}setConsent(false)}}/> Content disclosure: this content promotes a brand, product or service</label>{commercial&&<div className="commercialChoices"><label><input type="checkbox" checked={ownBrand} onChange={e=>{setOwnBrand(e.target.checked);setConsent(false)}}/> Your brand <span>— promotes yourself or your own business</span></label><label title={privacy==='SELF_ONLY'?'Branded content visibility cannot be set to private.':''}><input type="checkbox" checked={branded} disabled={privacy==='SELF_ONLY'} onChange={e=>{setBranded(e.target.checked);setConsent(false)}}/> Branded content <span>— promotes another brand or third party</span></label>{!commercialOK&&<div className="authError">You need to indicate if your content promotes yourself, a third party, or both.</div>}{ownBrand&&!branded&&<p>Your video will be labeled as “Promotional content”.</p>}{branded&&<p>Your video will be labeled as “Paid partnership”.</p>}{privacy==='SELF_ONLY'&&<p>Branded content visibility cannot be set to private.</p>}</div>}</div>
  </section>
  <section className="publisherCard publisherFinal"><small>3 · FINAL REVIEW</small><h2>Publish to TikTok</h2><p>Nothing is sent until you explicitly publish. Your video uploads directly from this browser to TikTok. After publishing, processing may take a few minutes before the post is visible on your profile.</p><div className="tiktokDeclaration">By posting, you agree to TikTok's {branded&&<><a href={BRANDED_URL} target="_blank" rel="noreferrer">Branded Content Policy</a> and </>}<a href={MUSIC_URL} target="_blank" rel="noreferrer">Music Usage Confirmation</a>.</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I reviewed the video, caption, audience, interaction and disclosure settings and expressly consent to send this content to TikTok.</label><button className="connectButton" disabled={!ready} onClick={publish}>{busy?'Working…':'Publish to TikTok →'}</button>{(busy||progress>0)&&<div><progress max="100" value={progress}/><p>{progress}%</p></div>}{status&&<div className="authNotice">{status}</div>}{error&&creator&&<div className="authError">{error}</div>}{publishId&&<button disabled={busy} onClick={checkStatus}>Check TikTok status</button>}</section>
 </div>
}
