'use client';

import { useEffect, useMemo, useState } from 'react';

const label={PUBLIC_TO_EVERYONE:'Public',MUTUAL_FOLLOW_FRIENDS:'Friends',FOLLOWER_OF_CREATOR:'Followers',SELF_ONLY:'Only me'};
const MUSIC_URL='https://www.tiktok.com/legal/page/global/music-usage-confirmation/en';
const BRANDED_URL='https://www.tiktok.com/legal/page/global/bc-policy/en';
async function jsonFetch(url,options){const r=await fetch(url,options);const j=await r.json().catch(()=>({}));if(!r.ok||(j.error?.code&&j.error.code!=='ok'))throw new Error(j.error?.message||j.error?.code||j.error||`Request failed (${r.status})`);return j}

export default function TikTokPublisher(){
 const [creator,setCreator]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [file,setFile]=useState(null),[preview,setPreview]=useState(''),[duration,setDuration]=useState(0),[title,setTitle]=useState(''),[privacy,setPrivacy]=useState('');
 const [comment,setComment]=useState(false),[duet,setDuet]=useState(false),[stitch,setStitch]=useState(false);
 const [commercial,setCommercial]=useState(false),[ownBrand,setOwnBrand]=useState(false),[branded,setBranded]=useState(false),[aigc,setAigc]=useState(false),[consent,setConsent]=useState(false);
 const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[publishId,setPublishId]=useState(''),[status,setStatus]=useState('');
 useEffect(()=>{(async()=>{try{const j=await jsonFetch('/api/tiktok/creator',{cache:'no-store'});setCreator(j.data)}catch(e){setError(e.message)}finally{setLoading(false)}})()},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const maxDuration=creator?.max_video_post_duration_sec||0;
 const durationOK=!file||(duration>0&&(!maxDuration||duration<=maxDuration));
 const commercialOK=!commercial||ownBrand||branded;
 const brandedPrivacyOK=!branded||privacy!=='SELF_ONLY';
 const ready=useMemo(()=>Boolean(file&&durationOK&&privacy&&consent&&commercialOK&&brandedPrivacyOK&&!busy),[file,durationOK,privacy,consent,commercialOK,brandedPrivacyOK,busy]);
 const step=file?privacy&&consent?3:2:1;
 function chooseFile(f){if(preview)URL.revokeObjectURL(preview);setFile(f||null);setPreview(f?URL.createObjectURL(f):'');setDuration(0);setProgress(0);setPublishId('');setStatus('');setError('');setConsent(false)}
 async function uploadChunks(uploadUrl,plan){const chunk=plan.chunk_size,count=plan.total_chunk_count,total=file.size;let start=0;for(let i=0;i<count;i++){const end=i===count-1?total:Math.min(start+chunk,total);const blob=file.slice(start,end);const r=await fetch(uploadUrl,{method:'PUT',headers:{'Content-Type':file.type||'video/mp4','Content-Length':String(blob.size),'Content-Range':`bytes ${start}-${end-1}/${total}`},body:blob});if(!(r.status===206||r.status===201||r.ok))throw new Error(`TikTok upload failed (${r.status})`);start=end;setProgress(Math.round(start/total*100))}}
 async function publish(){if(!ready)return;setBusy(true);setError('');setStatus('Initializing secure upload…');setProgress(0);try{const j=await jsonFetch('/api/tiktok/publish/init',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_size:file.size,title,privacy_level:privacy,disable_comment:!comment,disable_duet:!duet,disable_stitch:!stitch,brand_organic_toggle:commercial&&ownBrand,brand_content_toggle:commercial&&branded,is_aigc:aigc})});const d=j.data;if(!d?.upload_url||!d?.publish_id)throw new Error('TikTok did not return an upload session.');setPublishId(d.publish_id);setStatus('Uploading directly to TikTok…');await uploadChunks(d.upload_url,d.upload_plan);setStatus('Upload complete. TikTok is processing the post; this may take a few minutes.')}catch(e){setError(e.message);setStatus('')}finally{setBusy(false)}}
 async function checkStatus(){try{setBusy(true);const j=await jsonFetch('/api/tiktok/publish/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publish_id:publishId})});setStatus(j.data?.status||'Status received from TikTok.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <div className="publisherLoading"><span className="pulseDot"/>Loading TikTok creator permissions…</div>;
 if(error&&!creator)return <div className="publisherCard"><h2>TikTok connection needs attention</h2><p>{error}</p><a className="connectButton" href="/api/tiktok/connect">Reconnect TikTok →</a></div>;
 return <div className="publisherExperience">
  <div className="publisherRail"><div className={step>=1?'done':''}><b>01</b><span>Content</span></div><i/><div className={step>=2?'done':''}><b>02</b><span>Details</span></div><i/><div className={step>=3?'done':''}><b>03</b><span>Publish</span></div></div>
  <div className="publisherGrid">
   <section className="publisherCard creatorCard"><div className="cardEyebrow"><span className="eyebrowDot"/>AUTHORIZED CREATOR</div><div className="creatorRow">{creator?.creator_avatar_url&&<img src={creator.creator_avatar_url} alt=""/>}<div><h2>{creator?.creator_nickname||'TikTok creator'}</h2><p>@{creator?.creator_username||'connected account'}</p></div><b><span/>CONNECTED</b></div><div className="trustLine">Live permissions are refreshed from TikTok before every publishing session.</div></section>
   <section className="publisherCard mediaCard"><div className="cardEyebrow">01 · ORIGINAL CONTENT</div><div className="cardHeading"><h2>Select & preview</h2><span>MP4 · MOV · WebM</span></div><label className="dropZone"><input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={e=>chooseFile(e.target.files?.[0]||null)}/><span className="uploadGlyph">↑</span><strong>{file?'Replace video':'Choose a video'}</strong><em>{file?`${file.name} · ${(file.size/1048576).toFixed(1)} MB`:'Select original content from your device'}</em></label>{file&&<div className="previewShell"><video className="tiktokPreview" src={preview} controls playsInline onLoadedMetadata={e=>setDuration(e.currentTarget.duration||0)}/></div>}{duration>0&&<div className="mediaMeta"><span>{duration.toFixed(1)} sec</span><span>{maxDuration?`Limit ${maxDuration}s`:'Duration verified'}</span><b>READY</b></div>}{!durationOK&&<div className="authError">This video exceeds the posting duration TikTok returned for this creator.</div>}</section>
   <section className="publisherCard detailsCard"><div className="cardEyebrow">02 · POST DETAILS</div><h2>Make it yours</h2><label className="fieldLabel">Caption <span>{title.length}/2200</span></label><textarea value={title} maxLength={2200} onChange={e=>setTitle(e.target.value)} placeholder="Write a caption, add hashtags or mention creators…"/><label className="fieldLabel">Audience <span>Required</span></label><select value={privacy} onChange={e=>{setPrivacy(e.target.value);setConsent(false)}}><option value="" disabled>Choose who can view this post</option>{(creator?.privacy_level_options||[]).map(x=><option key={x} value={x} disabled={x==='SELF_ONLY'&&branded}>{label[x]||x}</option>)}</select>
    <div className="settingTitle">Interactions <span>Off by default — you choose</span></div><div className="publishChecks"><label className={creator?.comment_disabled?'disabled':''}><input type="checkbox" checked={comment} disabled={creator?.comment_disabled} onChange={e=>setComment(e.target.checked)}/><span><b>Comments</b><small>Allow conversation</small></span></label><label className={creator?.duet_disabled?'disabled':''}><input type="checkbox" checked={duet} disabled={creator?.duet_disabled} onChange={e=>setDuet(e.target.checked)}/><span><b>Duet</b><small>Allow Duet</small></span></label><label className={creator?.stitch_disabled?'disabled':''}><input type="checkbox" checked={stitch} disabled={creator?.stitch_disabled} onChange={e=>setStitch(e.target.checked)}/><span><b>Stitch</b><small>Allow Stitch</small></span></label><label><input type="checkbox" checked={aigc} onChange={e=>setAigc(e.target.checked)}/><span><b>AI-generated</b><small>Disclose AI content</small></span></label></div>
    <div className={`commercialBox ${commercial?'active':''}`}><label className="disclosureToggle"><input type="checkbox" checked={commercial} onChange={e=>{const on=e.target.checked;setCommercial(on);if(!on){setOwnBrand(false);setBranded(false)}setConsent(false)}}/><span><b>Commercial content disclosure</b><small>Turn on when this post promotes a brand, product or service.</small></span></label>{commercial&&<div className="commercialChoices"><label><input type="checkbox" checked={ownBrand} onChange={e=>{setOwnBrand(e.target.checked);setConsent(false)}}/><span><b>Your brand</b><small>Promotes yourself or your own business</small></span></label><label title={privacy==='SELF_ONLY'?'Branded content visibility cannot be set to private.':''} className={privacy==='SELF_ONLY'?'disabled':''}><input type="checkbox" checked={branded} disabled={privacy==='SELF_ONLY'} onChange={e=>{setBranded(e.target.checked);setConsent(false)}}/><span><b>Branded content</b><small>Promotes another brand or third party</small></span></label>{!commercialOK&&<div className="authError">Choose Your brand, Branded content, or both to continue.</div>}{ownBrand&&!branded&&<div className="disclosureResult">Promotional content label will be applied.</div>}{branded&&<div className="disclosureResult">Paid partnership label will be applied.</div>}</div>}</div>
   </section>
   <section className="publisherCard publisherFinal"><div className="finalIcon">✓</div><div className="finalCopy"><div className="cardEyebrow">03 · FINAL REVIEW</div><h2>Ready when you are.</h2><p>Nothing is sent automatically. Your video goes directly from this browser to TikTok only after you confirm and publish.</p><div className="tiktokDeclaration">By posting, you agree to TikTok's {branded&&<><a href={BRANDED_URL} target="_blank" rel="noreferrer">Branded Content Policy</a> and </>}<a href={MUSIC_URL} target="_blank" rel="noreferrer">Music Usage Confirmation</a>.</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I reviewed the video, caption, audience, interaction and disclosure settings and expressly consent to send this content to TikTok.</span></label></div><div className="finalAction"><button className="publishButton" disabled={!ready} onClick={publish}>{busy?<><span className="buttonSpinner"/>Publishing…</>:'Publish to TikTok →'}</button><small>{ready?'Everything is ready to publish.':'Complete the required review steps to continue.'}</small></div>{(busy||progress>0)&&<div className="progressWrap"><div className="progressTrack"><span style={{width:`${progress}%`}}/></div><div><b>{progress}%</b><span>{progress<100?'Uploading securely…':'Upload complete'}</span></div></div>}{status&&<div className={`statusPanel ${status==='PUBLISH_COMPLETE'?'success':''}`}><span>{status==='PUBLISH_COMPLETE'?'✓':'↗'}</span><div><b>{status==='PUBLISH_COMPLETE'?'Published successfully':'TikTok status'}</b><p>{status}</p></div></div>}{error&&creator&&<div className="authError">{error}</div>}{publishId&&<button className="statusButton" disabled={busy} onClick={checkStatus}>Refresh TikTok status ↻</button>}</section>
  </div>
 </div>
}
